'use client'
import {useEffect,useState} from 'react'
const OPT=[['yes','ÁNO, CHCEM'],['open','SOM OTVORENÝ/Á'],['no','NIE / TERAZ NIE']]
export default function PartnerClient({token}){const [data,setData]=useState(null),[step,setStep]=useState(0),[answers,setAnswers]=useState([]),[result,setResult]=useState(null),[err,setErr]=useState(''),[email,setEmail]=useState(''),[adult,setAdult]=useState(false),[marketing,setMarketing]=useState(false),[entered,setEntered]=useState(false)
 useEffect(()=>{fetch('/api/desire/deep?token='+encodeURIComponent(token)).then(r=>r.json()).then(setData).catch(()=>setErr('Pozvánku sa nepodarilo načítať.'))},[token])
 function enter(){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setErr('Zadajte platný e-mail.');return}if(!adult){setErr('Pre pokračovanie potvrďte vek 18+.');return}setErr('');setEntered(true)}
 async function ans(v){const n=[...answers];n[step]=v;setAnswers(n);if(step<data.test.questions.length-1){setStep(step+1);return}const r=await fetch('/api/desire/deep',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submitB',token,answers:n,email,adult:true,marketing})});const d=await r.json();if(!r.ok){setErr(d.error||'Vyhodnotenie zlyhalo.');return}setResult(d.result)}
 if(err&&!data)return <div className="deepStart"><h1>{err}</h1></div>; if(!data)return <div className="deepStart"><h1>Načítavam DESIRE…</h1></div>; if(!data.session)return <div className="deepStart"><h1>Pozvánka už nie je platná.</h1></div>
 if(!entered)return <div className="deepStart"><div className="deepIcon">❤️</div><small>POZVÁNKA DO MR GREY'S DESIRE</small><h1>Pozval vás {data.inviter||'váš partner'}.</h1><p>Partner už dokončil svoju časť testu <b>{data.test.title}</b>. Teraz je rad na vás. Jeho jednotlivé odpovede neuvidíte a on neuvidí vaše.</p><div className="partnerEntry"><input className="deepInput" type="email" placeholder="váš@email.sk" value={email} onChange={e=>setEmail(e.target.value)}/><label className="deepCheck"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)}/> Potvrdzujem, že mám minimálne 18 rokov.</label><label className="deepCheck"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/> Chcem dostávať nové testy, príbehy, hry a výhody zo sveta MR GREY’S. 😈 Voliteľné, súhlas môžem kedykoľvek odvolať.</label></div>{err&&<div className="joinError">{err}</div>}<button className="deepPrimary" onClick={enter}>ZAČAŤ MOJU ČASŤ →</button></div>
 if(result)return <div className="deepResult"><div className="deepIcon">{result.icon}</div><small>SPOLOČNÝ VÝSLEDOK</small><h1>{result.headline}</h1><p>{result.summary}</p>{result.discoveries.map((x,i)=><div className="resultDiscovery" key={i}><b>{x.title}</b><span>{x.text}</span></div>)}<div className="resultAction"><small>SKÚSTE SPOLU</small><p>{result.action}</p></div><a className="deepPrimary deepLink" href="/login">ULOŽENÉ V MR GREY'S →</a></div>
 const t=data.test,q=t.questions[step];return <div className="deepQuiz"><div className="deepProgress"><span>{t.icon} {t.title}</span><b>{step+1}/{t.questions.length}</b></div><div className="deepBar"><i style={{width:`${((step+1)/t.questions.length)*100}%`}}/></div><div className="deepPrivacy">🔒 Partner neuvidí vaše jednotlivé odpovede.</div><h2>{q}</h2><div className="deepOptions">{OPT.map(([v,l])=><button key={v} onClick={()=>ans(v)}>{l}</button>)}</div></div>}
