'use client'
import {useState} from 'react'
const OPT=[['yes','ÁNO, CHCEM'],['open','SOM OTVORENÝ/Á'],['no','NIE / TERAZ NIE']]
export default function DeepTestClient({test,slug}){
 const [session,setSession]=useState(null),[answers,setAnswers]=useState([]),[step,setStep]=useState(0),[partner,setPartner]=useState(''),[done,setDone]=useState(false),[invite,setInvite]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function start(){setBusy(true);setError('');const r=await fetch('/api/desire/deep',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start',slug})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Test sa nepodarilo spustiť.');return}setSession(d.session)}
 function answer(v){const next=[...answers];next[step]=v;setAnswers(next);if(step<test.questions.length-1)setStep(step+1);else setDone(true)}
 async function createInvite(){setBusy(true);setError('');const r=await fetch('/api/desire/deep',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submitA',id:session.id,answers,partnerEmail:partner})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Pozvánku sa nepodarilo vytvoriť.');return}setInvite(d.invite)}
 async function share(){if(navigator.share){await navigator.share({title:`MR GREY'S DESIRE — ${test.title}`,text:'Pozývam ťa dokončiť so mnou náš DESIRE test ❤️',url:invite});return}await navigator.clipboard.writeText(invite);alert('Pozvánka je skopírovaná.')}
 if(!session)return <div className="deepStart"><div className="deepIcon">{test.icon}</div><small>MR GREY'S DESIRE · HLBŠÍ TEST</small><h1>{test.title}</h1><p>{test.subtitle}</p><div className="deepPrivacy">🔒 Jednotlivé odpovede zostávajú súkromné. Do spoločného výsledku pustíme iba bezpečné spoločné objavy.</div>{error&&<div className="joinError">{error}</div>}<button className="deepPrimary" disabled={busy} onClick={start}>{busy?'OTVÁRAM…':'ZAČAŤ SVOJU ČASŤ'}</button></div>
 if(invite)return <div className="deepStart"><div className="deepIcon">❤️</div><small>VAŠA ČASŤ JE HOTOVÁ</small><h1>Teraz je rad na partnerovi.</h1><p>Pozvánku môžete poslať akokoľvek. Partner po otvorení najprv zadá svoj e-mail, potvrdí 18+ a až potom začne odpovedať.</p><div className="deepInviteLink">{invite}</div><button className="deepPrimary" onClick={share}>ZDIEĽAŤ POZVÁNKU</button><button className="deepGold" onClick={()=>navigator.clipboard.writeText(invite)}>KOPÍROVAŤ LINK</button></div>
 if(done)return <div className="deepStart"><div className="deepIcon">✓</div><small>1. ČASŤ DOKONČENÁ</small><h1>Pozvite partnera.</h1><p>E-mail nie je povinný. Ak ho zadáte, pošleme pozvánku aj e-mailom. Inak jednoducho vytvoríme súkromný link, ktorý môžete poslať cez WhatsApp, Messenger, SMS alebo natívne zdieľanie.</p><input className="deepInput" type="email" placeholder="partner@email.sk — voliteľné" value={partner} onChange={e=>setPartner(e.target.value)}/>{error&&<div className="joinError">{error}</div>}<button className="deepPrimary" disabled={busy} onClick={createInvite}>{busy?'PRIPRAVUJEM…':'VYTVORIŤ POZVÁNKU'}</button></div>
 const q=test.questions[step]
 return <div className="deepQuiz"><div className="deepProgress"><span>{test.icon} {test.title}</span><b>{step+1}/{test.questions.length}</b></div><div className="deepBar"><i style={{width:`${((step+1)/test.questions.length)*100}%`}}/></div><h2>{q}</h2><div className="deepOptions">{OPT.map(([v,l])=><button key={v} onClick={()=>answer(v)}>{l}</button>)}</div><button className="deepBack" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>← SPÄŤ</button></div>
}
