export const DEEP_TESTS={
 'my-dvaja':{icon:'❤️',title:'MY DVAJA',subtitle:'Blízkosť, pozornosť a veci, ktoré vás držia pri sebe.',about:'Test o vašom každodennom spojení — o pozornosti, spoločnom čase, malých gestách a rituáloch, ktoré vedia udržať iskru aj mimo veľkých momentov.',duration:'cca 10–15 min',discover:['čo vám obom pomáha cítiť sa bližšie','ktoré malé gestá majú pre vás najväčšiu hodnotu','aké spoločné rituály by vám mohli sedieť'],result:'Spoločný výsledok ukáže iba bezpečné oblasti, v ktorých sa stretávate, plus jeden konkrétny tip, ktorý môžete skúsiť spolu.',sensitive:false,questions:["Chcel/a by si, aby ste mali aspoň jeden večer mesačne iba pre seba bez telefónov?",
  "Je pre teba dôležité počuť od partnera častejšie, čo si na tebe váži?",
  "Chcel/a by si viac spontánnych dotykov a objatí počas bežného dňa?",
  "Pomohlo by vám plánovať si spoločný čas rovnako vedome ako pracovné povinnosti?",
  "Chcel/a by si, aby ste si častejšie povedali, čo vám v posledných dňoch urobilo radosť?",
  "Je pre teba príťažlivé prekvapiť partnera malým gestom bez konkrétneho dôvodu?",
  "Chcel/a by si skúsiť pravidelný krátky rituál, ktorý patrí iba vám dvom?",
  "Máš chuť objaviť spolu niečo nové mimo vašej bežnej rutiny?",
  "Chcel/a by si mať každý deň aspoň pár minút, keď sa vedome venujete iba jeden druhému?",
  "Cítiš sa bližšie, keď spolu niečo zažívate, než keď si iba vymieňate správy?",
  "Chcel/a by si častejšie plánovať malé rande aj bez špeciálnej príležitosti?",
  "Je pre teba dôležité, aby partner vedel, kedy potrebuješ blízkosť a kedy priestor?",
  "Chcel/a by si spolu vytvoriť zoznam malých vecí, ktoré vám robia radosť?",
  "Je pre teba dôležité, aby ste sa vedeli zasmiať aj počas náročného obdobia?",
  "Chcel/a by si vedome chrániť spoločný čas pred prácou a telefónmi?",
  "Chcel/a by si tento mesiac skúsiť jeden nový partnerský rituál?",
  "Chcel/a by si častejšie počuť spontánne „ľúbim ťa“ alebo „chýbaš mi“?",
  "Je pre teba dôležité cítiť, že ste tím aj pri obyčajných povinnostiach?",
  "Chcel/a by si sa občas nechať partnerom prekvapiť naplánovaným večerom?",
  "Cítiš sa milovanejšie cez dotyk než cez darčeky?",
  "Chcel/a by si si častejšie pripomínať, čo vás na sebe priťahovalo na začiatku?",
  "Je pre teba dôležité mať aspoň jeden spoločný ranný alebo večerný rituál?",
  "Chcel/a by si mať viac spoločných spomienok aj z úplne obyčajných dní?",
  "Chcel/a by si, aby ste si pravidelne povedali jednu vec, ktorú si na tom druhom vážite?"]},
 'bez-filtra':{icon:'💬',title:'BEZ FILTRA',subtitle:'Rozhovory, ktoré sa často odkladajú na neskôr.',about:'Test pre páry, ktoré chcú hovoriť otvorenejšie bez zbytočného tlaku. Zameriava sa na komunikáciu, uznanie, konflikty, neistoty a to, čo si často nechávame pre seba.',duration:'cca 10–15 min',discover:['kde si želáte viac otvorenosti','čo vám pomáha cítiť sa vypočutí','ktoré témy si zaslúžia pokojný rozhovor'],result:'Výsledok neukazuje, kto čo odpovedal. Zvýrazní len spoločné témy a jemné podnety na rozhovor bez hodnotenia alebo obviňovania.',sensitive:false,questions:["Chcel/a by si vedieť povedať partnerovi nepríjemnú vec bez strachu, že sa rozhovor zmení na hádku?",
  "Máš pocit, že sa vám niekedy ľahšie hovorí o praktických veciach než o pocitoch?",
  "Chcel/a by si, aby sa partner častejšie opýtal, čo práve potrebuješ, namiesto hádania?",
  "Pomohlo by vám mať pravidlo, že pri náročnom rozhovore najprv každý iba dopočúva druhého?",
  "Je niečo, za čo by si od partnera chcel/a dostávať viac uznania?",
  "Chcel/a by si vedieť otvorenejšie hovoriť o žiarlivosti alebo neistote bez obviňovania?",
  "Máš chuť hovoriť viac aj o tom, čo vo vzťahu funguje, nielen o problémoch?",
  "Chcel/a by si si s partnerom nastaviť jeden konkrétny spôsob, ako sa po konflikte znovu priblížiť?",
  "Chcel/a by si vedieť povedať „teraz potrebujem chvíľu pre seba“ bez toho, aby to partner bral ako odmietnutie?",
  "Je pre teba dôležité, aby po ospravedlnení nasledovala aj konkrétna zmena správania?",
  "Chcel/a by si otvorenejšie hovoriť o peniazoch bez napätia?",
  "Máte tému, ktorú obaja odkladáte, hoci viete, že by vám rozhovor pomohol?",
  "Chcel/a by si mať pri konflikte dohodnuté slovo alebo gesto, ktoré znamená „spomaľme“?",
  "Pomohlo by vám raz týždenne položiť si otázku: „Ako sa medzi nami teraz cítiš?“",
  "Je pre teba dôležité vedieť povedať „toto ma zranilo“ bez útoku?",
  "Je niečo pozitívne, čo partner robí často, ale ty mu to málo hovoríš?",
  "Chcel/a by si vedieť hovoriť o sexuálnych potrebách rovnako prirodzene ako o bežných veciach?",
  "Je pre teba dôležité, aby partner vedel priznať, keď si niečím nie je istý?",
  "Chcel/a by si si častejšie vypočuť partnerov názor bez potreby ho hneď meniť?",
  "Je pre teba dôležité cítiť, že partner nezľahčuje tvoje pocity?",
  "Chcel/a by si po hádke vedieť pomenovať, čo každý z vás v tej chvíli potreboval?",
  "Pomohlo by vám otvorenejšie hovoriť o očakávaniach od vzťahu?",
  "Chcel/a by si si ujasniť, ktoré témy sa nikdy nemajú riešiť v afekte?",
  "Je pre teba dôležité, aby ste dokázali hovoriť aj o nepríjemných veciach bez ironizovania a ponižovania?"]},
 'nasa-buducnost':{icon:'🔮',title:'NAŠA BUDÚCNOSŤ',subtitle:'To, kam chcete smerovať a čo chcete spolu zažiť.',about:'Test o spoločnom smerovaní — nie ako skúška kompatibility, ale ako spôsob, ako si pomenovať sny, priority a veci, na ktoré sa chcete ako pár tešiť.',duration:'cca 10–15 min',discover:['ktoré spoločné plány vás spájajú','čo chcete zažiť v najbližších rokoch','ako podporovať individuálne aj spoločné ciele'],result:'Výsledok vytiahne spoločné smerovanie a bezpečné témy na ďalší rozhovor. Citlivé rozdiely sa negamifikujú ani nehodnotia.',sensitive:false,questions:["Je pre teba dôležité mať s partnerom spoločnú predstavu o najbližších troch rokoch?",
  "Chcel/a by si spolu viac hovoriť o bývaní, cestovaní a životnom štýle, ktorý chcete?",
  "Je pre teba dôležité, aby ste mali podobné priority pri peniazoch a voľnom čase?",
  "Chcel/a by si si raz za čas spolu vytvoriť zoznam vecí, ktoré chcete zažiť?",
  "Je pre teba dôležité vedieť, čo partner vníma ako svoj osobný sen?",
  "Chcel/a by si, aby ste vedome chránili partnerský čas aj pri väčších životných zmenách?",
  "Máš chuť plánovať niečo, na čo sa budete obaja tešiť už niekoľko mesiacov dopredu?",
  "Je pre teba dôležité, aby sa vaše individuálne ciele navzájom podporovali?",
  "Chcel/a by si vedieť, kde by ste obaja radi žili o päť rokov?",
  "Je pre teba dôležité mať spoločnú predstavu o pomere práce a súkromia?",
  "Chcel/a by si otvorene hovoriť o tom, akú úlohu má vo vašej budúcnosti rodina?",
  "Je pre teba dôležité mať podobný pohľad na šetrenie a väčšie výdavky?",
  "Chcel/a by si spolu vytvoriť jeden spoločný cieľ na najbližší rok?",
  "Je pre teba dôležité, aby mal každý z vás priestor aj na vlastné sny?",
  "Chcel/a by si mať spoločný zoznam miest, ktoré chcete navštíviť?",
  "Je niečo, čo by si chcel/a do jedného roka zažiť ako pár prvýkrát?",
  "Je pre teba dôležité vedieť, ako si partner predstavuje ideálny bežný deň o desať rokov?",
  "Chcel/a by si hovoriť o tom, čo by ste urobili, keby jeden z vás dostal veľkú pracovnú príležitosť inde?",
  "Je pre teba dôležité mať podobný pohľad na to, čo znamená úspešný život?",
  "Chcel/a by si vedieť, čo partner nechce vo svojej budúcnosti obetovať?",
  "Je pre teba dôležité chrániť partnerský čas aj počas rodičovstva alebo náročnej kariéry?",
  "Chcel/a by si spolu hovoriť o tom, ako si predstavujete domov a bývanie?",
  "Je pre teba dôležité vedieť, ako chce partner tráviť sviatky a rodinné udalosti?",
  "Chcel/a by si mať jeden veľký spoločný sen, ku ktorému budete smerovať spolu?"]},
 'intimita':{icon:'🔥',title:'INTIMITA',subtitle:'Dotyk, atmosféra, tempo a to, čo vás k sebe priťahuje.',about:'Hlbší test o tom, čo medzi vami vytvára napätie a blízkosť — tempo, dotyk, atmosféra, vedenie, outfit a nové veci, ktoré by ste možno chceli skúsiť.',duration:'cca 10–15 min',discover:['čo vás oboch prirodzene priťahuje','aké tempo a atmosféra vám sedia','ktoré nové intímne prvky sú spoločným áno alebo otvorenosťou'],result:'Konkrétne intímne témy sa ukážu iba vtedy, keď je medzi vami bezpečný vzájomný priestor. Jednostranné alebo odmietnuté odpovede ostávajú súkromné.',sensitive:true,questions:["Chcel/a by si mať viac času na pomalé zvádzanie bez ponáhľania?",
  "Lákal by ťa večer, pri ktorom si navzájom vyberiete outfit?",
  "Chcel/a by si častejšie hovoriť partnerovi priamo, aký dotyk alebo tempo ti vyhovuje?",
  "Láka ťa skúsiť intímny večer so zaviazanými očami?",
  "Vzrušuje ťa, keď jeden z vás na chvíľu preberie jasnejšie vedenie?",
  "Chcel/a by si niekedy vyskúšať jemné ťahanie za vlasy alebo pevnejšie uchopenie za boky vopred dohodnutým spôsobom?",
  "Lákalo by ťa zaradiť do večera erotickú pomôcku, ktorú si vyberiete spolu?",
  "Chcel/a by si si s partnerom otvorene povedať jednu vec, ktorú by si v intimite chcel/a zažívať častejšie?",
  "Láka ťa dlhšia masáž, ktorá sa nemusí hneď zmeniť na sex?",
  "Chcel/a by si, aby partner častejšie inicioval intimitu?",
  "Láka ťa viac svetlo a očný kontakt než úplná tma?",
  "Vzrušuje ťa pomalé vyzliekanie viac než rýchly prechod k intimite?",
  "Chcel/a by si si navzájom ukázať, kde a ako sa ťa má partner dotýkať?",
  "Láka ťa hra s tempom — chvíľu veľmi pomaly a potom intenzívnejšie?",
  "Chcel/a by si si vopred dohodnúť večer, keď jeden z vás pripraví celú atmosféru?",
  "Chcel/a by si si s partnerom vytvoriť vlastný wishlist intímnych vecí?",
  "Láka ťa skúsiť večer bez penetrácie, iba s dotykmi, bozkami a napätím?",
  "Je pre teba príťažlivé, keď partner počas intimity viac rozpráva?",
  "Láka ťa použiť šatku alebo masku na oči ako súčasť hry?",
  "Chcel/a by si skúsiť viac dominantného vedenia bez bolesti alebo ponižovania?",
  "Je pre teba vzrušujúce, keď partner jasne povie, čo chce?",
  "Chcel/a by si mať bezpečný rozhovor o tom, čo je pre teba v sexe jasné NIE?",
  "Láka ťa skúsiť novú polohu alebo prostredie, ktoré ste ešte spolu neskúsili?",
  "Chcel/a by si, aby ste si po intímnom večeri povedali, čo sa každému z vás páčilo najviac?"]},
 'tajne-tuzby':{icon:'😈',title:'TAJNÉ TÚŽBY',subtitle:'Iba to, v čom sa bezpečne stretnete. Ostatné zostáva súkromné.',about:'Najodvážnejšia vrstva DESIRE. Fantázie, role, dominancia, pomôcky a tajné úlohy — s pravidlom, že výsledok ukáže iba to, kde sa vaše túžby bezpečne stretnú.',duration:'cca 10–15 min',discover:['ktoré fantázie máte spoločné','kde je medzi vami zvedavosť bez tlaku','aké odvážnejšie veci môžete bezpečne preskúmať spolu'],result:'Ak jeden z vás pri citlivej téme odpovie NIE, konkrétna túžba sa v spoločnom výsledku vôbec nezobrazí. Žiadne odhaľovanie jednostranných fantázií.',sensitive:true,questions:["Láka ťa roleplay, pri ktorom si na večer vytvoríte nové postavy?",
  "Lákal by ťa večer s jasne dohodnutou dominantnou a submisívnou rolou?",
  "Chcel/a by si niekedy skúsiť mäkké putá alebo bezpečné manžety?",
  "Lákalo by ťa poslať partnerovi počas dňa súkromnú zvodnú fotku ako tajnú úlohu?",
  "Vzrušuje ťa predstava, že partner vyberie, čo si na súkromný večer oblečieš?",
  "Lákalo by ťa dohodnúť si večer, počas ktorého jeden z vás určuje tempo bozkov a dotykov?",
  "Chcel/a by si si s partnerom vytvoriť vlastné bezpečné slovo pre odvážnejšie hry?",
  "Máš fantáziu, o ktorej by si sa s partnerom rád/rada porozprával/a, aj keby ste ju nikdy nezrealizovali?",
  "Láka ťa nechať partnera pripraviť pre teba prekvapenie bez toho, aby si poznal/a detaily?",
  "Lákalo by ťa skúsiť jemnú hru s príkazmi, kde môžeš kedykoľvek povedať STOP?",
  "Vzrušuje ťa predstava, že sa na partnera chvíľu iba pozeráš bez možnosti dotýkať sa?",
  "Chcel/a by si skúsiť intímnu hru s bodovaním alebo odmenami?",
  "Láka ťa použiť v súkromí odvážnejší outfit alebo kostým?",
  "Lákalo by ťa, keby partner pripravil zoznam troch tajných úloh na večer?",
  "Chcel/a by si si navzájom napísať jednu fantáziu anonymne a potom ich spolu prečítať?",
  "Lákalo by ťa vytvoriť si spoločný zoznam „áno / možno / nie“ pre odvážnejšie túžby?",
  "Lákalo by ťa vyskúšať bezpečnú hru s ľahkým zviazaním rúk?",
  "Chcel/a by si si s partnerom vytvoriť vlastné bezpečné slovo pre odvážnejšie hry?",
  "Láka ťa predstava, že jeden z vás na chvíľu úplne určuje tempo v dohodnutých hraniciach?",
  "Lákala by ťa zmyslová hra, pri ktorej nevieš, aký dotyk príde ako ďalší?",
  "Chcel/a by si bezpečne preskúmať fantáziu, ktorú si doteraz partnerovi nepovedal/a?",
  "Láka ťa viac hra s mocou a vedením než samotná pomôcka?",
  "Chcel/a by si niekedy spolu vybrať novú erotickú pomôcku alebo doplnok?",
  "Je pre teba príťažlivé mať odvážnejšiu fantáziu iba ako spoločné tajomstvo, aj keď ju nikdy nezrealizujete?"]}
}
const DEEP_EXTRA_SK={"my-dvaja":["Chcel/a by si mať každý deň aspoň pár minút, keď sa vedome venujete iba jeden druhému?","Cítiš sa bližšie, keď spolu niečo zažívate, než keď si iba vymieňate správy?","Chcel/a by si, aby ste si častejšie plánovali malé rande aj bez špeciálnej príležitosti?","Je pre teba dôležité, aby partner vedel, kedy potrebuješ blízkosť a kedy priestor?","Chcel/a by si spolu vytvoriť zoznam malých vecí, ktoré vám robia radosť?","Je pre teba dôležité, aby ste sa vedeli zasmiať aj počas náročného obdobia?","Chcel/a by si, aby ste si vedome chránili spoločný čas pred prácou a telefónmi?","Chcel/a by si tento mesiac skúsiť jeden nový partnerský rituál?"],"bez-filtra":["Chcel/a by si vedieť povedať „teraz potrebujem chvíľu pre seba“ bez toho, aby to partner bral ako odmietnutie?","Je pre teba dôležité, aby sa ospravedlnenie skončilo aj konkrétnou zmenou správania?","Chcel/a by si vedieť otvorenejšie hovoriť o peniazoch bez napätia?","Máte tému, ktorú obaja odkladáte, hoci viete, že by vám rozhovor pomohol?","Chcel/a by si mať pri konflikte dohodnuté slovo alebo gesto, ktoré znamená „spomaľme“?","Pomohlo by vám raz týždenne položiť si otázku: „Ako sa medzi nami teraz cítiš?“","Je pre teba dôležité vedieť povedať „toto ma zranilo“ bez útoku?","Je niečo pozitívne, čo partner robí často, ale ty mu to málo hovoríš?"],"nasa-buducnost":["Chcel/a by si vedieť, kde by ste obaja radi žili o päť rokov?","Je pre teba dôležité mať spoločnú predstavu o tom, koľko času chcete venovať práci a koľko súkromiu?","Chcel/a by si otvorene hovoriť o tom, akú úlohu má vo vašej budúcnosti rodina?","Je pre teba dôležité mať podobný pohľad na šetrenie a väčšie výdavky?","Chcel/a by si spolu vytvoriť jeden spoločný cieľ na najbližší rok?","Je pre teba dôležité, aby mal každý z vás priestor aj na vlastné sny?","Chcel/a by si mať spoločný zoznam miest, ktoré chcete navštíviť?","Je niečo, čo by si chcel/a do jedného roka zažiť ako pár prvýkrát?"],"intimita":["Láka ťa dlhšia masáž, ktorá sa nemusí hneď zmeniť na sex?","Chcel/a by si, aby partner častejšie inicioval intimitu?","Láka ťa viac svetlo a očný kontakt než úplná tma?","Vzrušuje ťa pomalé vyzliekanie viac než rýchly prechod k intimite?","Chcel/a by si si navzájom ukázať, kde a ako sa ťa má partner dotýkať?","Láka ťa hra s tempom — chvíľu veľmi pomaly a potom intenzívnejšie?","Chcel/a by si vopred dohodnúť večer, keď jeden z vás pripraví celú atmosféru?","Chcel/a by si si s partnerom vytvoriť vlastný wishlist intímnych vecí, ktoré môžete postupne objavovať?"],"tajne-tuzby":["Láka ťa nechať partnera pripraviť pre teba prekvapenie bez toho, aby si poznal/a detaily?","Lákalo by ťa skúsiť jemnú hru s príkazmi, kde môžeš kedykoľvek povedať STOP?","Vzrušuje ťa predstava, že sa na partnera chvíľu iba pozeráš bez dotyku?","Chcel/a by si skúsiť intímnu hru s bodovaním alebo odmenami?","Láka ťa použiť v súkromí odvážnejší outfit alebo kostým?","Lákalo by ťa, keby partner pripravil zoznam troch tajných úloh na večer?","Chcel/a by si si navzájom napísať jednu fantáziu anonymne a potom ich spolu prečítať?","Lákalo by ťa vytvoriť si spoločný zoznam „áno / možno / nie“ pre odvážnejšie túžby?"]}
Object.entries(DEEP_EXTRA_SK).forEach(([slug,extra])=>{if(DEEP_TESTS[slug])DEEP_TESTS[slug].questions=[...DEEP_TESTS[slug].questions,...extra]})

export function buildResult(test,a=[],b=[]){
 const found=[]
 test.questions.forEach((q,i)=>{
  const x=a[i],y=b[i]
  if(x==='yes'&&y==='yes') found.push({kind:'strong',title:'Obaja to chcete objaviť',text:q})
  else if((x==='yes'&&y==='open')||(x==='open'&&y==='yes')||(x==='open'&&y==='open')) found.push({kind:'open',title:'Je tu spoločný priestor na objavovanie',text:q})
  else if(!test.sensitive && x && y && x!==y) found.push({kind:'talk',title:'Téma na pokojný rozhovor',text:'Túto oblasť vnímate trochu inak. Skúste si povedať, čo by každému z vás pomohlo cítiť sa v nej dobre.'})
 })
 const unique=[]; const seen=new Set()
 for(const f of found){const k=f.text; if(!seen.has(k)){seen.add(k);unique.push(f)}}
 return {title:test.title,icon:test.icon,headline:'Toto sme medzi vami objavili.',summary:unique.length?'Máte niekoľko bezpečných miest, kde sa môžete stretnúť, rozprávať a skúšať nové veci.':'Aj ticho je výsledok. V tomto kole sme nenašli nič, čo by bolo vhodné tlačiť do spoločného výsledku.',discoveries:unique.slice(0,6),action:unique[0]?.text||'Vyberte si tento týždeň jeden pokojný večer len pre vás dvoch.'}
}
