const COPY={
 sk:{account_welcome:['Vitajte v MR GREY’S WORLD','Váš súkromný účet je pripravený. Tu budú pokope vaše DESIRE výsledky, sledovania a odomknutý obsah.','OTVORIŤ MÔJ ÚČET'],club_welcome:['Vitajte v MR GREY’S CLUB 👑','Členstvo je aktívne. Odomkli ste Club, všetkých päť hlbších DESIRE testov, Date Night a členské výhody.','VSTÚPIŤ DO CLUBU'],payment_failed:['Platbu za Club sa nepodarilo spracovať','Skontrolujte prosím platobnú metódu, aby váš prístup k MR GREY’S CLUB zostal aktívny.','SPRAVOVAŤ ČLENSTVO'],membership_cancelled:['Vaše členstvo bolo zrušené','Prístup zostáva aktívny do konca už zaplateného obdobia. Zakúpené samostatné produkty vám zostávajú.','MÔJ ÚČET'],deep_purchase:['DESIRE test je odomknutý ❤️','Test {test} je natrvalo pridaný do vášho účtu a môžete sa k nemu kedykoľvek vrátiť.','OTVORIŤ TEST'],reactivation:['V MR GREY’S na vás čaká niečo nové','Od vašej poslednej návštevy pribudol nový obsah. Vybrali sme jednu vec, ktorou sa oplatí pokračovať.','POZRIEŤ, ČO JE NOVÉ'],desire_invite:['Partner vás pozýva do DESIRE ❤️','Váš partner dokončil svoju časť testu {test}. Teraz je rad na vás. Vaše jednotlivé odpovede zostávajú súkromné.','OTVORIŤ DESIRE'],desire_result:['Vaše DESIRE je pripravené ❤️','Obaja ste dokončili {test}. Spoločný výsledok máte uložený aj vo svojom MR GREY’S účte.','ZOBRAZIŤ VÝSLEDOK'],story_next:['Nová časť vášho príbehu je vonku 😈','Pokračovanie, na ktoré ste čakali, je pripravené v MR GREY’S CLUB.','OTVORIŤ POKRAČOVANIE'],journey_step:['Ďalší krok DESIRE je pripravený','Vaša spoločná cesta pokračuje. Nový krok je odomknutý a čaká na vás v účte.','POKRAČOVAŤ']},
 cs:{desire_invite:['Partner vás zve do DESIRE ❤️','Váš partner dokončil svou část testu {test}. Teď jste na řadě vy. Vaše jednotlivé odpovědi zůstávají soukromé.','OTEVŘÍT DESIRE'],desire_result:['Vaše DESIRE je připravené ❤️','Oba jste dokončili {test}. Společný výsledek máte uložený i ve svém MR GREY’S účtu.','ZOBRAZIT VÝSLEDEK']},
 pl:{desire_invite:['Partner zaprasza Cię do DESIRE ❤️','Partner ukończył swoją część testu {test}. Teraz Twoja kolej. Wasze indywidualne odpowiedzi pozostają prywatne.','OTWÓRZ DESIRE'],desire_result:['Wasze DESIRE jest gotowe ❤️','Oboje ukończyliście {test}. Wspólny wynik znajdziecie również na koncie MR GREY’S.','ZOBACZ WYNIK']},
 en:{desire_invite:['Your partner invited you to DESIRE ❤️','Your partner completed their part of {test}. Now it’s your turn. Your individual answers stay private.','OPEN DESIRE'],desire_result:['Your DESIRE is ready ❤️','You both completed {test}. Your shared result is also saved in your MR GREY’S account.','VIEW RESULT']}
}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
export async function sendServiceEmail({to,lang='sk',template,data={}}){
 const key=process.env.RESEND_API_KEY, from=process.env.MRGREYS_EMAIL_FROM; if(!key||!from||!to) return {skipped:true}
 const base=(COPY[lang]||COPY.sk)[template]||COPY.sk[template]; if(!base) return {skipped:true}
 const fill=s=>s.replaceAll('{test}',data.test||'DESIRE'); const [subject,lead,cta]=base.map(fill); const href=data.href||'https://mrgrey.sk'
 const html=`<!doctype html><html><body style="margin:0;background:#050407;color:#f7f2f8;font-family:Arial,sans-serif"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 14px"><table width="100%" style="max-width:620px;background:#0b0810;border:1px solid #372641;border-radius:22px"><tr><td style="padding:38px"><div style="letter-spacing:.22em;color:#d3ad62;font-size:11px">MR GREY'S WORLD</div><h1 style="font-family:Georgia,serif;font-size:34px;margin:14px 0;color:#fff">${esc(subject)}</h1><p style="color:#c5b8cb;line-height:1.7;font-size:15px">${esc(lead)}</p><a href="${esc(href)}" style="display:inline-block;margin-top:18px;padding:14px 22px;border-radius:999px;background:#8f2bd1;color:#fff;text-decoration:none;font-weight:700">${esc(cta)}</a><p style="margin-top:28px;color:#776d7d;font-size:11px">MR GREY'S · Pre páry, ktorým nestačí rutina.</p></td></tr></table></td></tr></table></body></html>`
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html})}); if(!r.ok) return {ok:false,error:await r.text()}; return {ok:true}
}
