"use client"
import {useEffect,useState} from 'react'
const STORY_NAMES={spolocnicka:'Denník luxusnej spoločníčky',tatry:'Víkend v Tatrách',kino:'Stretla som ho v kine'}
export default function AccountClient({initialProfile,role,fullAccess,clubActive,subscriptions,results,journey}){
 const [p,setP]=useState(initialProfile),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[subs,setSubs]=useState(subscriptions||[])
 function set(k,v){setP(x=>({...x,[k]:v}))}
 async function save(e){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Uloženie zlyhalo.');setP(d.profile);setMsg('✓ Zmeny sú uložené.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function toggleStory(s){const active=!s.is_active;const r=await fetch('/api/account/story-follow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:s.story_slug,active,email_enabled:s.email_enabled,club_enabled:s.club_enabled})});if(r.ok)setSubs(v=>v.map(x=>x.story_slug===s.story_slug?{...x,is_active:active}:x))}
 return <main className="accountMain">
  <section className="accountHero"><small>👤 MÔJ ÚČET</small><h1>Všetko o vašom MR GREY'S<br/><em>na jednom mieste.</em></h1><p>Profil, členstvo, upozornenia, sledované Stories aj história vašich DESIRE výsledkov.</p><div className="accountStatus"><span>{fullAccess?'👑 INTERNÝ PRÍSTUP':clubActive?'✓ AKTÍVNY CLUB':'○ ÚČET'}</span><b>{String(role||'member').toUpperCase()}</b></div></section>
  <div className="accountGrid"><section className="accountCard"><small>OSOBNÉ ÚDAJE</small><h2>Profil</h2><form onSubmit={save} className="accountForm"><label>MENO ALEBO PREZÝVKA<input value={p.display_name||''} onChange={e=>set('display_name',e.target.value)}/></label><label>E-MAIL<input value={p.email||''} disabled/></label><label>DÁTUM NARODENIA<input type="date" value={p.date_of_birth||''} onChange={e=>set('date_of_birth',e.target.value)}/></label><label>JAZYK<select value={p.preferred_language||'sk'} onChange={e=>set('preferred_language',e.target.value)}><option value="sk">Slovenčina</option><option value="cs">Čeština</option><option value="pl">Polski</option><option value="en">English</option></select></label><button disabled={busy}>{busy?'UKLADÁM…':'ULOŽIŤ ZMENY →'}</button>{msg&&<div className="accountMsg">{msg}</div>}</form></section>
  <section className="accountCard"><small>🔔 KOMUNIKÁCIA</small><h2>Čo chcete dostávať?</h2><label className="settingSwitch"><div><b>Upozornenia v Clube</b><span>Nové pokračovania, DESIRE kroky a dôležité novinky.</span></div><input type="checkbox" checked={p.notify_club!==false} onChange={e=>set('notify_club',e.target.checked)}/></label><label className="settingSwitch"><div><b>Vyžiadané e-mailové upozornenia</b><span>Napríklad pokračovanie Story, ktoré sami sledujete.</span></div><input type="checkbox" checked={p.notify_email!==false} onChange={e=>set('notify_email',e.target.checked)}/></label><label className="settingSwitch"><div><b>Marketing a inšpirácie</b><span>Voliteľné ponuky, novinky a vybrané tipy.</span></div><input type="checkbox" checked={!!p.marketing_consent} onChange={e=>set('marketing_consent',e.target.checked)}/></label><button className="ghostSave" onClick={save}>ULOŽIŤ NASTAVENIA →</button></section></div>
  <section className="accountSection" id="follow"><div className="sectionTitle"><small>😈 MOJE SLEDOVANIA</small><h2>Pokračovania, ktoré nechcete zmeškať.</h2></div>{subs.length===0?<div className="accountEmpty">Zatiaľ nesledujete žiadne pokračovanie. Pri seriálovej Story kliknite na „Upozorniť ma na pokračovanie“.</div>:<div className="followList">{subs.map(s=><article key={s.story_slug}><div><small>STORY</small><b>{STORY_NAMES[s.story_slug]||s.story_slug}</b><span>{s.is_active?'Upozornenie je zapnuté':'Upozornenie je vypnuté'}</span></div><button className={s.is_active?'on':''} onClick={()=>toggleStory(s)}>{s.is_active?'VYPNÚŤ':'ZNOVA ZAPNÚŤ'}</button></article>)}</div>}</section>
  <section className="accountSection"><div className="sectionTitle"><small>❤️ MOJE DESIRE</small><h2>Vaše výsledky zostávajú pokope.</h2></div>{results.length===0?<div className="accountEmpty">Po dokončení hlbšieho DESIRE sa váš spoločný výsledok uloží sem. Staršie výsledky neprepisujeme.</div>:<div className="resultList">{results.map(r=><a href={`/desire/results/${r.session_id}`} key={r.id}><div><small>{new Date(r.created_at).toLocaleDateString('sk-SK')}</small><b>{r.result_snapshot?.title||r.test_slug}</b><span>{r.result_snapshot?.coupleType||'Vaše spoločné DESIRE'}</span></div><i>POZRIEŤ VÝSLEDOK →</i></a>)}</div>}</section>
  <section className="accountSection"><div className="sectionTitle"><small>✨ DESIRE JOURNEY</small><h2>Postupne. Nie všetko naraz.</h2></div>{journey?<div className="journeyAccount"><b>{journey.status==='active'?'AKTÍVNA CESTA':'DOKONČENÉ'}</b><span>Aktuálny krok: {Number(journey.current_step||0)+1}</span>{journey.next_unlock_at&&<span>Ďalší krok: {new Date(journey.next_unlock_at).toLocaleString('sk-SK')}</span>}<a href="/club/desire/journey">OTVORIŤ JOURNEY →</a></div>:<div className="accountEmpty">Journey ešte nemáte spustenú. Prvý krok dostanete hneď, ďalší sa odomkne podľa vopred oznámeného intervalu.</div>}</section>
 </main>
}
