import LanguageSwitcher from "../../components/LanguageSwitcher"
const topics=[
  ['❤️','VZŤAHY & PSYCHOLÓGIA','Ako si zostať blízki, hovoriť o túžbach, zvládať rozdiely a nenechať rutinu prevziať kontrolu.'],
  ['🔥','SEX & INTIMITA','Otvorené témy o príťažlivosti, orgazme, dotykoch, fantáziách a tom, prečo niekedy partneri hovoria menej, než cítia.'],
  ['😈','BDSM & OBJAVOVANIE','Súhlas, hranice, dôvera, bezpečnosť, dominancia, submisivita a prvé bezpečné kroky vo dvojici.'],
  ['🧠','MUŽI & ŽENY','Ako môžu muži a ženy rozdielne prežívať príťažlivosť, blízkosť, odmietnutie, túžbu a komunikáciu.']
]
export default function Academy(){return <div className="academyPage"><header className="clubTop"><a className="clubBrand" href="/">MR GREY'S <span>ACADEMY</span></a><div className="clubTools"><LanguageSwitcher/><a href="/">← WORLD</a></div></header><main>
<section className="academyHero" style={{backgroundImage:"linear-gradient(90deg,rgba(5,4,7,.98),rgba(5,4,7,.72) 48%,rgba(5,4,7,.2)),url('/card-academy-clean.jpg')"}}><div><small>MR GREY'S ACADEMY · PRIPRAVUJEME</small><h1>Veci, o ktorých sa veľa premýšľa.<br/><em>Ale málo hovorí.</em></h1><p>Pripravujeme miesto, kde budeme otvorene hovoriť o vzťahoch, sexe, intimite, túžbach a psychológii partnerstva — bez trápnych poučiek a bez zbytočných tabu.</p><div className="academyFormats"><span>🎬 VIDEO LEKCIE</span><span>📖 ČLÁNKY & NÁVODY</span><span>🎧 AUDIO</span><span>❤️ CVIČENIA PRE PÁRY</span></div></div></section>
<section className="academyQuestions"><small>ČO BUDEME OTVÁRAŤ</small><h2>Otázky, ktoré si ľudia kladú.<br/>Odpovede, ktoré sa často boja hľadať.</h2><div className="academyQuestionGrid"><span>Prečo ženy niekedy predstierajú orgazmus?</span><span>Čo si partneri želajú, ale nepovedia?</span><span>Ako hovoriť o fantáziách bez tlaku?</span><span>Prečo sa po rokoch stráca iskra — a ako ju znova prebudiť?</span><span>Ako rozdielne môžu muži a ženy vnímať príťažlivosť?</span><span>Kde končí hra a začínajú hranice?</span></div></section>
<section className="academyTopicGrid">{topics.map(t=><article key={t[1]}><b>{t[0]}</b><h3>{t[1]}</h3><p>{t[2]}</p><span>PRIPRAVUJEME →</span></article>)}</section>
<section className="bondageTeaser" style={{backgroundImage:"linear-gradient(90deg,rgba(5,4,7,.97),rgba(5,4,7,.62),rgba(5,4,7,.18)),url('/card-academy-clean.jpg')"}}><div><small>🪢 PRIPRAVUJEME NOVÝ KURZ</small><h2>BONDAGE BASICS</h2><p>Prvý praktický kurz bondage od MR GREY'S ACADEMY. Od výberu povrazu cez komunikáciu, súhlas a bezpečnosť až po základné uzly a techniky krok za krokom.</p><div><span>🎬 Video lekcie</span><span>📖 Návody</span><span>🪢 Praktické ukážky</span><span>❤️ Pre páry</span></div></div></section>
<section className="academyClubCta"><small>👑 MR GREY'S CLUB</small><h2>Členovia budú pri tom prví.</h2><p>Vybraný Academy obsah bude súčasťou členstva. Nové lekcie, články a kurzy sa vám objavia priamo v členskom dashboarde.</p><a className="btn" href="/club/join">VSTÚPIŤ DO CLUBU →</a></section>
</main></div>}
